# Generated by Django 4.1.6 on 2023-02-15 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agricultor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='')),
                ('precio', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('agricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultor.agricultor')),
            ],
        ),
    ]
